### ISSUE TITLE
fn.func.curried does not work in Python 2

### ISSUE THREAD

**Issue by jacobbridges** [fnpy/fn.py#10]
```python
from fn.func import curried

@curried
def f(a, b):
    return a + b

print(f(1)(5))
```

The above code yields "6" in Python 3.5.1, but in Python 2.7.11 it produces the following error:

```shell
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(f(1)(5))
  File "/home/jacob/.pyenv/versions/2.7.11/lib/python2.7/site-packages/fn/func.py", line 83, in _curried
    return curried(partial(func, *args, **kwargs))
  File "/home/jacob/.pyenv/versions/2.7.11/lib/python2.7/site-packages/fn/func.py", line 69, in curried
    @wraps(func)
  File "/home/jacob/.pyenv/versions/2.7.11/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'functools.partial' object has no attribute '__module__'
```

**Comment by cad106uk** [comment]
I have a fix for this. I was trying to get it merged into the old fn.py. How should I get it merged into this project?

**Comment by cad106uk** [comment]
Aha, after much swearing at github the interface starts to make sense. Fix here #11

**Comment by jacobbridges** [comment]
Ah, thank you for submitting this! I'm reviewing it right now.

You have reminded me to go through the open pull requests on the old fn.py and ping the author's to resubmit their pull requests here.

**Comment by jacobbridges** [comment]
This was fiexd in PR #11 

Thanks @cad106uk !!
