### ISSUE TITLE
Discuss: What coding style guide should fn.py use?

### ISSUE THREAD

**Issue by jacobbridges** [fnpy/fn.py#14]
@fnpy/fn-py-team 

We have a pending pull request (#13) to fix some PEP8 problems with the project, but before merging that into master it has been suggested that we review as a team what style guide to follow. 

Once we decide upon a coding standard (such as max column length, alphabetical imports, snake case vs camel case, etc.) I will add it to the project's wiki. I don't think the linter you use should matter, just the style rules.

----

I think this is a productive topic, *but* it could easily reduce into people squabbling over personal preferences and maintenance further being delayed. So, with that in mind I am only going to let us discuss this for a week, _maybe_ two weeks if some people don't get in their say quick enough. I just don't want this to deter development on the project longer than it should.

**Comment by cad106uk** [comment]
I am in favour of Pep8, with an extended line length. It's simple it's standard and we can move on to something more interesting :-)

**Comment by microamp** [comment]
Regarding line length, I personally prefer 99 chars to the standard 79.

> Some teams strongly prefer a longer line length. For code maintained exclusively or primarily by a team that can reach agreement on this issue, it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters), provided that comments and docstrings are still wrapped at 72 characters. (https://www.python.org/dev/peps/pep-0008/#maximum-line-length)

**Comment by jacobbridges** [comment]
@microamp do you still prefer keeping the docstrings to 72 characters?

Also, @Digenis and @low-ghost, do either of you have an opinion?

**Comment by low-ghost** [comment]
I'm for Pep8, but I don't have much of an opinion on line length. 79 seems limiting. 100 or 120 seem more realistic and I'd prefer something in that range, but again, not too opinionated. I haven't heard about a preference for shorter docstrings than code and I don't really get the intention, but I don't have a problem with it. I'm for alphabetical imports as long as that's a standard supported ide feature or automatic formatter feature (not a problem in vim, but others?).

**Comment by microamp** [comment]
> @microamp do you still prefer keeping the docstrings to 72 characters?

I'm not too fussed TBH. Personally, I mostly worry about code and its readability.

**Comment by Digenis** [comment]
I don't care about alphabetical imports
but they also don't bother me so it's up to you.

Regarding the line length, as I already said,
even if it sounds outdated on modern terminals
short lines still help solve merge conflict problems.
When displaying a diff3, long lines become a bit of a headache.
(Short lines can even prevent merge conflicts
 but I don't want to use this as an argument)

**Comment by cad106uk** [comment]
Shall we just use PEP8? That way we don't have to go through this any more. It is becoming a bike shed

**Comment by jacobbridges** [comment]
I'll be typing up a proper "Contribution style guide" tonight, but this is what I have gathered:

We will be using PEP8 with the following additions/modifications:
 - Line length will be extended to 99 characters
 - Imports will be alphabetical and follow the following format:
```python
# Standard library imports
## import <module> sorted alphabetically
import os
import sys

## from <module> import <symbol> sorted alphabetically on <module>
from collections import OrderedDict
from json import dumps, loads

# Related third party imports
# same sub-styling as standard library imports


# Local modules
## same sub-styling as standard library imports
```

----

Before I write the style guide, is everyone ok with this?

**Comment by jacobbridges** [comment]
OK, the wiki page is up: https://github.com/fnpy/fn.py/wiki

I'm closing this issue (it can always be reopened if any of you want to discuss this further).
