### ISSUE TITLE
__complex__/__int__/__float__/__round__

### ISSUE THREAD

**Issue by flying-sheep** [fnpy/fn.py#17]
can we do [those](https://docs.python.org/3/reference/datamodel.html#object.__complex__)?

**Comment by flying-sheep** [comment]
no we can’t :cry: 

```pytb
TypeError: __int__ returned non-int (type function)
```

**Comment by jacobbridges** [comment]
Could you provide a use case?

**Comment by flying-sheep** [comment]
a currently open notebook:

```python
sorted(acc, key=lambda a: int(a[3:]))
```

should be

```python
sorted(acc, key=int(_[3:]))
```

**Comment by jacobbridges** [comment]
Ah, I see. We could investigate adding it as a feature.

**Comment by Digenis** [comment]
> Called to implement the built-in functions complex(), int(), float() and round().
> **Should return a value of the appropriate type.**

This similar to https://github.com/kachayev/fn.py/issues/65
I already explain there.
We can't do this with all magic methods.

I think we should add to the documentation a sentence
saying that `_` requires good knowledge of the [python data model](https://docs.python.org/3/reference/datamodel.html)

**Comment by jacobbridges** [comment]
Thanks @Digenis for the insight. I will read through the python data model again and refresh my memory before updating the documentation.
