### ISSUE TITLE
Updating the 'How to find me' wiki section

### ISSUE THREAD

**Issue by cad106uk** [fnpy/fn.py#2]
How do we want people to contact us?

**Comment by jacobbridges** [comment]
I was just thinking the same thing -- I don't know how comfortable people are giving out their emails, so I don't know that we can start an email chain.

For the time being I created a [Gitter chat room](https://gitter.im/fnpy/fn.py) for the project until we can decide on a more permanent solution.

**Comment by EntilZha** [comment]
Google groups list is probably a decent idea. I like gitter + issues here though

**Comment by jacobbridges** [comment]
Accidentally closed the issue, was trying to comment.

I think Google groups is a good idea, though I have no experience with managing one. Will have a look around at other open source projects this weekend to see how they manage their groups.

**Comment by jacobbridges** [comment]
The "How to find me" section of the README has been updated to reflect our current situation. If we start using Google groups then I will add a link to the README.
