### ISSUE TITLE
Would this be published to pypi?

### ISSUE THREAD

**Issue by anthonylau** [fnpy/fn.py#20]
I come across https://github.com/kachayev/fn.py and found that is inactive

**Comment by jacobbridges** [comment]
This project is published to PyPi as `fn.py`. (https://pypi.python.org/pypi/fn.py/0.4.4)

Kachayev's original repo was published as `fn`. (https://pypi.python.org/pypi/fn/0.4.3)

So all you have to do is `pip install fn.py`

**Comment by mrkaspa** [comment]
you should update the readme then

**Comment by jacobbridges** [comment]
@mrkaspa, good call. It's done.
