### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by cgarciae** [fnpy/fn.py#22]
I take that the pypi repo is not being update with the code on this fork?

**Comment by cgarciae** [comment]
For those who might run into this, do

    pip uninstall fn
    pip install fn.py

**Comment by jacobbridges** [comment]
Hi @cgarciae, thanks for checking out our fork. We have tried contacting the maintainer of the original repo several times and merging this project into the original, but he has never responded. I am closing this issue since your question has been answered.
