### ISSUE TITLE
Improve "methods" for underscore

### ISSUE THREAD

**Issue by cgarciae** [fnpy/fn.py#23]
When you write something like this

    _.split(',')

you intuitively expect that at some point you are going to get a string `s` and excecute `s.split(',')`. In practical terms you want this

    _.split(',')("hello,world") # "hello,world".split(',') == ["hello", "world"]

instead you get strange behaviour that interprets things like this

    _.split(',')("hello,world") # ','.split('"hello,world") == [',']

I prefer the first way of interpreting this. I've modified the code to achieve this:

    def __getattr__(self, name):
        attr_name = _random_name()

        def method_proxy(*args, **kwargs):
            def f(x):
                method = getattr(x, name)
                return method(*args, **kwargs)

            return self.__class__(
                F(f) << F(self),
                "getattr(%s, %%(%s)r)" % (self._format, attr_name),
                dict(
                    list(self._format_args.items()) + [(attr_name, name)]
                ),
                self._arity
            )

        return method_proxy

**Comment by Digenis** [comment]
What if you only need an attrgetter? This will undo the current behaviour.
There's no perfect way to solve this.
`_.call()` is reserved for constructing methodcallers.

**Comment by jacobbridges** [comment]
Hi @cgarciae, sorry I came to the conversation late. I understand your confusion with the example you have provided, but the dot syntax on the underscore is meant to be an attribute getter. You could use the `_.call()` as @Digenis mentioned, or you could just swap the strings in your example:

```python
# This first calls "attrgetter" on the string "hello,world", which returns <function str.split>
# then it passes that function the second string, ','. 
_.split('hello,world')(',') == ['hello', 'world']
```

**Comment by cgarciae** [comment]
Hi @Digenis  and @jacobbridges 

I know about the `call` method, but my point is that the current behavior is counter intuitive to the concept of the `_`. Take the expression

```python
_ + 5
```
its equivalent to

```python
lambda x: x + 5
```
so you'd expect that

```python
_.method(arg)
```
would be equivalent to
```python
lambda x: x.method(arg)
```
but instead its
```python
lambda x: arg.method(x)
```
`_` is sort a placeholder, the behavior I am proposing would be more consistent with with that concept.

**Comment by jacobbridges** [comment]
@cgarciae, what would you expect the last line of this example to output?

```python
from fn import _
from collections import namedtuple

Point = namedtuple('Point', 'x y')
points = [Point(3, 5), Point(-10, 6), (-8, -3)]

list( map( _.x, points ) )  # Extra spacing around parenthesis for clarity
```

**Comment by cgarciae** [comment]
@jacobbridges

Point taken. You want to promote field access over method calling.

**Comment by Digenis** [comment]
You can define a different underscore
for method chaining similar
`__ = type('MethodChain', (Underscore,), {'__getattr__': (lambda s, n: F(s.call, n))})()`
