### ISSUE TITLE
Deploy on PyPi

### ISSUE THREAD

**Issue by jacobbridges** [fnpy/fn.py#5]
What is everyone's thoughts on deploying this project to the Python package index? I know one already exists, but we don't have access to change that one.

If we agree to make this fork available on PyPi, what should we change the name to?

**Comment by mario-campos** [comment]
*fn* is already taken, so how about *fn.py*?

**Comment by jacobbridges** [comment]
Can we have periods in a python package name?

**Comment by jacobbridges** [comment]
Turns out we can...it is now deployed in PyPi as fn.py. 

You'll need to uninstall the previous _fn_ first, because if you have both installed Python will not know which to import on `import fn`.

**Comment by Digenis** [comment]
79cc69c27803ae2d575f137dd01bfbf42d8d95f4 can be followed
by adding to setup.py something like the following
https://github.com/maxtepkeev/python-redmine/blob/master/setup.py#L7-L26
(both projects use apache 2 licence)
