### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by jacobbridges** [fnpy/fn.py#6]
Currently the project version is at 0.4.3 ([here](https://github.com/fnpy/fn.py/blob/master/fn/__init__.py)). Should we continue incrementing the current version (minor for bug fixes, major for new features), or should we bump the version to 1.0.0 and start "fresh"?

**Comment by mario-campos** [comment]
I say keep as-is. That doesn't seem like a good reason to just bump it up to 1.0.0.

**Comment by jacobbridges** [comment]
So if we keep it as the current version, since it is less than version 1 people may assume it is still in development? 

Basically I don't want to make the same mistake as some other projects that start v0.x then suddenly jump to version v5.x

**Comment by low-ghost** [comment]
I kind of like the jump to 1.0.0, basically what io did in the fork from node. However, if we do plan on making some breaking changes early on, the version will climb quickly. Maybe minor bumps until we feel a bit more settled on anything new, then a major 1.0.0. And yes, I do assume it is still in development if it is < 1.

**Comment by mario-campos** [comment]
Yeah, what @low-ghost said. I say we keep in line with [Semantic Versioning](http://semver.org/), which basically says that API-breaking changes should require a major version number bump (1.0.0 to 2.0.0). Minor non-API-breaking changes (like optimizations) should require a minor version number bump (1.0.0 to 1.1.0). And patches for bug fixes and other such things should require a patch number bump (1.0.0 to 1.0.1). In theory, if we keep all the breaking changes < 1.0.0, then *fn.py* shouldn't be bumping up to 4, 5, 6, etc.

**Comment by jacobbridges** [comment]
That makes sense. Ok I will change the current milestones to reflect what we have agreed upon here.

Thanks for your thoughts guys!
