### ISSUE TITLE
Split out large tests.py file into a directory

### ISSUE THREAD

**Issue by jacobbridges** [fnpy/fn.py#8]
The current [tests.py](https://github.com/fnpy/fn.py/blob/master/tests.py) file should be split out into several logical files beneath a "test" directory. This is a better project design and makes the project easier to integrate a test runner. (nose, nose2, etc.)

**Comment by jacobbridges** [comment]
How should versioning work for this issue @low-ghost and @mario-campos? It isn't "new functionality", so it shouldn't be a minor version bump. And it isn't a bug fix, since the tests are currently working. It's just restructuring.

How should I bump the version on this change?

**Comment by mario-campos** [comment]
Well, if you want to put a version number to it, I'd put it at a minor version bump.

*But* not every change requires a version bump. We could lump this refactor under the next (major, minor, etc) release, along with other changes.

**Comment by jacobbridges** [comment]
Thanks to @cad106uk, the tests are now separated into their own directory.

I am using the command `python -m unittest discover ./tests` to run the tests, but sadly the `discover` module did not exist in Python 2.6, so I have to look into a test runner to run the tests in all supported versions. 

I was going to default to [nose](http://nose.readthedocs.io/en/latest/), but their website recommends nose2 or py.test. Does anyone have a preference?

**Comment by mario-campos** [comment]
I've only ever implemented nose, but assertpy uses py.test and it looks pretty nice.

**Comment by jacobbridges** [comment]
I've added a `test.py` file to the repo for now (see commit 6b72b5706b983319577bba49e03b14a62843bad3). This will satisfy Travis until we implement a test runner. I'll close this issue out since the original issue of "splitting tests into a directory" has been completed.

**Comment by cad106uk** [comment]
Personally I have been using nose. I haven't put any thought to which unittest framework we should use.
